name: Build release

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
